require('d.plugins')
require('d.settings')
require('d.mappings')
require('d.cmp')
require('d.lsp')
require('d.treesitter')
require('d.refactorconf')
require('d.lualineconf')
require('d.bufferlineconf')
require('d.devicons')
require('d.alphaconf')
require('d.comment')
require('d.nvimtreeconf')
require('d.nfconf')

--require('d.themerconf')
--require('d.dlua')

