source $HOME/.config/nvim/vim-plug/plugins.vim
source $HOME/.config/nvim/vim-plug/packer.lua
source $HOME/.config/nvim/general/settings.vim
source $HOME/.config/nvim/keys/mappings.vim
source $HOME/.config/nvim/themes/everforest.vim
source $HOME/.config/nvim/themes/airline.vim
source $HOME/.config/nvim/lua/lsp.lua
source $HOME/.config/nvim/lua/refactorconfig.lua
source $HOME/.config/nvim/lua/troubleconfig.lua
